### ISSUE TITLE
Trophy road or Path of Legends feature 

### ISSUE THREAD

**Issue by EthanNielsen** [pyclashbot/py-clash-bot#265]
Since only Trophy Road and Path of Legends are the only game modes that give chests to unlock, I think it would be great to provide an option for the bot to play that game mode. Also, if the bot can be taught to play on meta decks like royal giant, etc... That'd be great to up the chances of winning and receiving a chest to unlock.

**Describe the solution you'd like**
Provide an option for the bot to play Trophy Road or Path of Legends.

**Describe alternatives you've considered**
Adding instructions for the bot to play other on meta decks like royal giant or lavahound, etc...

**Additional context**
That's all folks.

**Comment by martinmiglio** [comment]
This feature has been added in the latest pre-releases and will be included in a stable release soon!

Use v2.0.6 release candidates.
