### ISSUE TITLE
Stuck on Configuring VM

### ISSUE THREAD

**Issue by martinmiglio** [pyclashbot/py-clash-bot#319]
When creating a new emulator, the bot will freeze on `configuring vm` step.

Version: master
OS: Windows 11

**Comment by Estkli-Wandeln** [comment]
same to me

**Comment by Estkli-Wandeln** [comment]
Q: How can I fix the bot taking a long time to Configure VM?
A: Closing the Multiple Instance Manager MEmu window while the bot is running can fix this issue.

It worked for me :)

**Comment by martinmiglio** [comment]
> Q: How can I fix the bot taking a long time to Configure VM? A: Closing the Multiple Instance Manager MEmu window while the bot is running can fix this issue.

This is the manual solution, it has seemed to work for everyone experiencing this issue.
I would like to eventually automate this solution, so I am tracking this issue here 👍
