### ISSUE TITLE
Error on "Check to see if the match was a "Win" or a "Loss"

### ISSUE THREAD

**Issue by raymundlee26** [pyclashbot/py-clash-bot#331]
**Describe the bug**
The bug happens when it checks to see the result of the match, it then crashes and starts a new cycle. basically it just does the first battle and skips all other things after, then goes back to square one.

**To Reproduce**
in my case i just start and after 1 battle it automatically restarts. sometimes it restarts ok but it freezes and stops eventually

**Expected behavior**
A restart of the program, and an eventual stoppage.
it piles up bot crashes until it crashes altogether

**Screenshots**
I did not take any screenshot. i will update if i get one.

**Desktop (please complete the following information):**
 Windows 10
 Latest version
 

**Additional context**
None

**Comment by martinmiglio** [comment]
Thanks for the report, this is a known issue. It seems that this is related to the latest update to Clash Royale, but the exact change is not quite known.

**Comment by martinmiglio** [comment]
This issue has been fixed in [v2.0.2rc4](https://github.com/pyclashbot/py-clash-bot/releases/tag/v2.0.2rc4).

**Comment by raymundlee26** [comment]
after i updated the bot to the latest version which was yesterday, i seem
to have a different problem regarding "waiting for clash main menu", it
stays in the main menu for about 200-250 secs and crashes. i dont think it
recognizes the main menu.

im sorry i cant be of any help to the program, i hope reporting bugs
actively will help with solving the problems, i will also upload my logs so
you can figure out what happened in the mean time.
