### ISSUE TITLE
your app is fully out of screen

### ISSUE THREAD

**Issue by furjac** [pyclashbot/py-clash-bot#388]
This is a very important thing u have to add for low end or less resolution screen user its such a drag
![image](https://github.com/pyclashbot/py-clash-bot/assets/81816200/da643591-64ef-4455-8862-b486f0e07cfd)
you guys also made the screen not resizable see im using 1366x768
plz fix this
the window literally going below screen even i tried hiding taskbar still it doesnt work

**Comment by matthewmiglio** [comment]
just disable Memu Docking for now. Will investigate later

**Comment by martinmiglio** [comment]
This is an issue we would like to address. Since v2.0.3 we have updated the layout of the user interface but only as pre-releases. Could you test out [the latest pre-release, v2.0.6rc15](https://github.com/pyclashbot/py-clash-bot/releases/tag/v2.0.6rc15) and let me know if this fits your display size?

**Comment by furjac** [comment]
Sure I'll test it and tell u back

**Comment by furjac** [comment]
now its like this
![image](https://github.com/pyclashbot/py-clash-bot/assets/81816200/d93a2391-5a73-46d3-b071-7f8307b67c1c)
i think its ok but i have like made the taskbar clear using a app from microsoft store

**Comment by martinmiglio** [comment]
Try [v2.0.6rc26](https://github.com/pyclashbot/py-clash-bot/releases/tag/v2.0.6rc26). This version includes a new button which allows users to collapse the top half of the interface.

**Comment by furjac** [comment]
ohh i see i will use thanks
