### ISSUE TITLE
Can't login to google play store on vm

### ISSUE THREAD

**Issue by stefffkec** [pyclashbot/py-clash-bot#414]
**Describe the bug**
When I go to google play store and try to sign in, the screen becomes black (but doesn't freeze, it's only google play store)

**To Reproduce**
1. Go to the starting menu
2. Click on play store
3. Click on login (the green button)
4. The screen is black

**Expected behavior**
Normal login page

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Display resolution: 1920x1080

**Comment by aneeshraman** [comment]
Try going to system settings (in the memu program and not inside the emulator) and try changing the render mode from DirectX to OpenGL, then restart it. It would help log into the play store. However, if you (close the window), and want to access the play store again after running the program, then you would have to change the setting again.

**Comment by martinmiglio** [comment]
This is a known issue with the MEmu Emulator. To install the Clash Royale app, sideload an APK.
