### ISSUE TITLE
Cant log into Google Play on MEMU

### ISSUE THREAD

**Issue by Gownie09** [pyclashbot/py-clash-bot#415]
When i try to sign into my Google account it keeps coming up with a error saying there was a problem communicating with Google servers try again later.
![MEmu 06_08_2024 22_42_36](https://github.com/user-attachments/assets/2a149a0b-395b-4710-946b-4de5c6db6987)

**Comment by martinmiglio** [comment]
This is a known issue with the MEmu Emulator. To install the Clash Royale app, sideload an APK.
