### ISSUE TITLE
Clash Royale does not launch on Memu

### ISSUE THREAD

**Issue by sc7171** [pyclashbot/py-clash-bot#439]
**Describe the bug**
Upon startup, Clash Royale stops "working" on memu. Tested on different windows systems, and with the latest versions of memu. I have tried different graphics settings (low to high, opengl and directx, etc.)
**To Reproduce**
1. Install latest version of memu
2. Use pyclashbot to launch an instance
3. Login to google play and install clash royale
4. launch clash royale
**Expected behavior**
Successful launch of clash royale.
**Desktop (please complete the following information):**
OS: Windows 11 and 10
Version: latest stable pyclashbot (2.1.1) and memu 
**Additional context**
I think it may be a memu issue as this has been an issue in the past. perhaps a workaround is possible?

**Comment by d5ze** [comment]
Hello, I'm facing the same problem have you found a solution? I tried everything but still the same results

**Comment by martinmiglio** [comment]
After the latest game update, Clash Royale has issues launching on MEmu. This should be fixed by the MEmu team soon.

**Comment by martinmiglio** [comment]
This issue has been solved with the latest version of MEmu
