### ISSUE TITLE
Can we open more than one Memu? and a few questions

### ISSUE THREAD

**Issue by bypan94** [pyclashbot/py-clash-bot#467]
Is there an automatic bot suitable for Clash Royale for the current 2v2? I also mean the classic 1v1 without trophy boost. Can we make this program for more than 1 memu? Or does it only work for 1 memu? Please answer I would be glad.

**Comment by bypan94** [comment]
hello, I have never used python so I am asking you. Do you have a Discord
channel or a place where I can reach you? I am using py-clash-bot v2.1.1
version and I leave the program open on the legends path. Do you have any
suggestions?

Martin Miglio ***@***.***>, 25 Kas 2024 Pzt, 16:21 tarihinde
şunu yazdı:

**Comment by martinmiglio** [comment]
You do not need to know how to use Python to use the bot.

There is a discord community linked in the README.
